# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import List

def compute_math_reward(predictions: List[str], references: List[str]) -> List[float]:
    """
    Computes a list of scores (1.0 for correct, 0.0 for incorrect) for math problems.
    This logic is adapted from the OpenCompass MATHVerifyEvaluator.

    Args:
        predictions (List[str]): A list of answers generated by the model.
        references (List[str]): A list of ground truth answers.

    Returns:
        List[float]: A list of scores, where each score is 1.0 or 0.0.
    """
    try:
        from latex2sympy2_extended import NormalizationConfig
        from math_verify import (ExprExtractionConfig,
                                 LatexExtractionConfig, parse, verify)
    except ImportError:
        raise ImportError('Failed to import required modules for math verification. '
                          'Please install the necessary packages: '
                          'pip install math_verify latex2sympy2_extended')

    if len(predictions) != len(references):
        raise ValueError("Length of predictions and references must be the same.")

    scores = []
    for pred, ref in zip(predictions, references):
        # 1. Parse the ground truth reference answer
        # The reference is expected to be a clean LaTeX string, e.g., "x^2 + 1"
        # We wrap it in '$...$' to ensure it's treated as a LaTeX environment
        ref_with_env = f'${ref}$'
        gold_parsed = parse(
            ref_with_env,
            extraction_mode='first_match',
            extraction_config=[
                LatexExtractionConfig(),
                ExprExtractionConfig(),
            ],
        )

        score = 0.0
        if len(gold_parsed) != 0:
            # 2. Parse the model's prediction
            # The prediction is a full string, and we need to find the boxed answer
            answer_parsed = parse(
                pred,
                extraction_config=[
                    LatexExtractionConfig(
                        normalization_config=NormalizationConfig(
                            nits=False,
                            malformed_operators=False,
                            basic_latex=True,
                            # equations=True, # Deprecated, handled by parser now
                            boxed='all',
                            units=True,
                        ),
                        # Ensures that \boxed{} or \fbox{} is tried first
                        boxed_match_priority=0,
                        try_extract_without_anchor=False,
                    )
                ],
                extraction_mode='first_match',
            )

            # 3. Verify if the parsed prediction is mathematically equivalent to the reference
            if answer_parsed: # Only verify if we successfully parsed an answer
                try:
                    is_correct = verify(answer_parsed, gold_parsed)
                    score = float(is_correct) * 10 if is_correct is not None else 0.0
                except Exception:
                    # The verify function can sometimes raise exceptions on complex expressions
                    score = 0.0
        
        scores.append(score)

    return scores
